// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/permissions/users/sources/delete": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions_users_sources"
                ],
                "summary": "(root-only)",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delete.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/delete.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/delete.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/delete.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/delete.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/permissions/users/sources/get/get_by_sources": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions_users_sources"
                ],
                "summary": "(root-only)",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/get_by_sources.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/get_by_sources.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/get_by_sources.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/get_by_sources.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/permissions/users/sources/get/get_by_user_ids": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions_users_sources"
                ],
                "summary": "(must be root if asking for other users)",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/get_by_user_ids.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/get_by_user_ids.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/get_by_user_ids.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/get_by_user_ids.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/permissions/users/sources/set": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions_users_sources"
                ],
                "summary": "(root-only)",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Response body",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/records/bunkering": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bunkering.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bunkering.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/bunkering.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bunkering.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/sources/get": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "(root-only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_get.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_get.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_get.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/sources/set": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "(root-only)",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_set.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_set.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_set.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_sources_set.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/users/auth": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_auth.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_auth.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_auth.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_auth.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_auth.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/users/create": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "(root-only)",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.TypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/create.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/create.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/create.TypeRes"
                        }
                    }
                }
            }
        },
        "/api/v2/users/get": {
            "post": {
                "security": [
                    {
                        "HeadersUserId": []
                    },
                    {
                        "HeadersSession": []
                    },
                    {
                        "Cookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "(root-only)",
                "responses": {
                    "200": {
                        "description": "Request Body",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_get.TypeRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_get.TypeRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_get.TypeRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main_src_models_variants_variant_2_io_users_get.TypeRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bunkering.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "averageTags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "end": {
                            "type": "string"
                        },
                        "latestTags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "source": {
                            "type": "string"
                        },
                        "start": {
                            "type": "string"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "bunkering.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "averageRecord": {
                            "$ref": "#/definitions/global_model.TypeRecord"
                        },
                        "latestRecord": {
                            "$ref": "#/definitions/global_model.TypeRecord"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "create.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "name": {
                            "type": "string"
                        },
                        "pass": {
                            "type": "string"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "create.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "integer"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "delete.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/global_model.TypeDeleteSourceUser"
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "delete.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "feel free to override"
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "get_by_sources.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "sources": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "get_by_sources.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/global_model.TypeSourceUsers"
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "get_by_user_ids.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "userIds": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "get_by_user_ids.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/global_model.TypeUserSources"
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "global_model.TypeDeleteSourceUser": {
            "type": "object",
            "properties": {
                "sourceSerial": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "global_model.TypeRecord": {
            "type": "object",
            "additionalProperties": {}
        },
        "global_model.TypeSourceUsers": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/global_model.TypeUser"
                    }
                }
            }
        },
        "global_model.TypeUser": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "integer"
                },
                "username": {
                    "$ref": "#/definitions/global_model.TypeUsername"
                }
            }
        },
        "global_model.TypeUserSources": {
            "type": "object",
            "properties": {
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "$ref": "#/definitions/global_model.TypeUser"
                }
            }
        },
        "global_model.TypeUsername": {
            "type": "string",
            "enum": [
                "root"
            ],
            "x-enum-varnames": [
                "CONST_USERS_ROOT_USERNAME"
            ]
        },
        "main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "idUser": {
                            "type": "integer"
                        },
                        "readPermission": {
                            "type": "boolean"
                        },
                        "sourceSerial": {
                            "type": "string"
                        },
                        "writePermission": {
                            "type": "boolean"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "main_src_models_variants_variant_2_io_permissions_users_sources_set.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "feel free to override"
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "main_src_models_variants_variant_2_io_sources_get.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "main_src_models_variants_variant_2_io_sources_set.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "source": {
                            "type": "string"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "main_src_models_variants_variant_2_io_sources_set.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "feel free to override"
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "main_src_models_variants_variant_2_io_users_auth.TypeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "pass": {
                            "type": "string"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "main_src_models_variants_variant_2_io_users_auth.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "auth": {
                            "type": "boolean"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "session": {
                            "type": "string"
                        }
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "main_src_models_variants_variant_2_io_users_get.TypeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/global_model.TypeUser"
                    }
                },
                "metadata": {
                    "description": "override, but better not",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "never override",
                    "type": "object",
                    "properties": {
                        "errCode": {
                            "type": "integer"
                        },
                        "errDesc": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Cookie": {
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        },
        "HeadersSession": {
            "type": "apiKey",
            "name": "Session",
            "in": "header"
        },
        "HeadersUserId": {
            "type": "apiKey",
            "name": "User-Id",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
